# Generated by Django 4.1.5 on 2023-01-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='subnet',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_num',
            field=models.IntegerField(null=True),
        ),
    ]
