# Generated by Django 4.1.5 on 2023-01-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_alter_team_name_alter_team_subnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='passed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
