# Based on https://github.com/thecourseforum/theCourseForum2/blob/dev/.github/workflows/continuous-integration.yml
name: Continuous Integration

on:
  pull_request:
    branches:
      - '*'
  # The following is needed to run tests upon direct push to main
  push:
    branches: [main]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run Pylint
        run: pylint --load-plugins pylint_django scoreboard
